# Generated by Django 5.2.4 on 2025-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('capital', models.FloatField()),
                ('expenses', models.FloatField()),
                ('emi', models.FloatField()),
                ('liquidity_need', models.FloatField()),
                ('dependents', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('knowledge', models.FloatField()),
                ('comfort_with_negatives', models.FloatField()),
                ('market_awareness', models.FloatField()),
                ('experience', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
